import java.util.*;
import java.io.*;

public abstract class Employee implements Serializable{
	//serialVersionUID is specified to avoid java.io.InvalidClassException due to autogenerated serialVersionUID
	private static final long serialVersionUID = 6529685098267757690L;

	String empID, empName, empIC, empPosition, empGender, empPassword;
	Calendar dateOfBirth, dateOfHired;
	boolean fulltime, checkedSalary;
	double totalSalary, bonus;

	public Employee(String empID, String empName, String empIC, String empPosition, String empGender, Calendar dateOfBirth, Calendar dateOfHired){
		this.empID = empID;
		this.empName = empName;
		this.empIC = empIC;
		this.empPosition = empPosition;
		this.dateOfBirth = dateOfBirth;
		this.dateOfHired = dateOfHired;
		this.empGender = empGender;
		checkedSalary = false;
		totalSalary = -1;
		bonus = -1;
		empPassword = "";
	}

	public abstract void calculateSalary(Vector<Position> vector) throws Exception;	

	public abstract void reset();
}

